import Link from 'next/link';
import { ArrowRight, HeartHandshake, MapPin, ShieldCheck } from 'lucide-react';
import CareCostCalculator from '@/components/CareCostCalculator';
import OpenCareChatButton from '@/components/OpenCareChatButton';

const careLevels = [
  { number: '01', title: 'Independent Living', copy: 'A maintenance-light community life with more time for what you enjoy.', detail: 'For active older adults who want connection and convenience.' },
  { number: '02', title: 'Assisted Living', copy: 'A helping hand with daily routines while keeping choice and independence.', detail: 'For support with meals, medication, dressing, or bathing.' },
  { number: '03', title: 'Memory Care', copy: 'Purposeful routines and specialized support for memory changes.', detail: 'For families navigating dementia or Alzheimer’s care.' },
  { number: '04', title: 'Skilled Nursing', copy: 'Around-the-clock clinical care and rehabilitation when needs change.', detail: 'For complex medical needs or recovery after a hospital stay.' },
];

export default function Home() {
  return <>
    <section className="relative overflow-hidden rounded-[2rem] bg-[#e8efe9] px-6 py-12 sm:px-10 sm:py-16 lg:px-14 lg:py-20"><div className="absolute -right-16 -top-16 h-72 w-72 rounded-full border-[36px] border-white/60" /><div className="relative max-w-3xl"><p className="eyebrow">Local guidance for the Triangle</p><h1 className="mt-5 font-serif text-5xl leading-[1.04] text-ink sm:text-6xl">Empathetic senior care placement <em className="text-moss">at no cost to your family.</em></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-700">When care decisions feel heavy, a local advisor helps you understand your options, compare nearby communities, and take one clear next step at a time.</p><div className="mt-8 flex flex-wrap gap-3"><OpenCareChatButton className="flex min-h-14 items-center gap-3 rounded-full bg-ink px-6 font-bold text-white transition hover:bg-moss">Talk with an advisor</OpenCareChatButton><Link href="#care-costs" className="flex min-h-14 items-center rounded-full border border-ink/20 bg-white/90 px-6 font-bold text-ink">Explore typical costs</Link></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-sm font-semibold text-slate-700"><span className="flex items-center gap-2"><ShieldCheck size={18} className="text-moss" /> Free to families</span><span className="flex items-center gap-2"><MapPin size={18} className="text-moss" /> Local, face-to-face help</span></div></div></section>
    <section className="py-16 sm:py-20"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">Understand the choices</p><h2 className="mt-3 max-w-2xl font-serif text-4xl leading-tight sm:text-5xl">Care should fit the person, not the other way around.</h2></div><OpenCareChatButton className="flex min-h-12 items-center gap-2 font-bold text-moss">Ask which may fit <ArrowRight size={17} /></OpenCareChatButton></div><div className="mt-9 grid gap-3 sm:grid-cols-2">{careLevels.map(level => <article key={level.number} className="rounded-2xl border border-slate-200 bg-white p-6 transition hover:border-moss/50 hover:shadow-soft"><div className="flex items-start justify-between gap-4"><div><span className="eyebrow">{level.number} / care type</span><h3 className="mt-2 text-xl font-extrabold">{level.title}</h3></div><HeartHandshake className="shrink-0 text-moss" size={23} /></div><p className="mt-4 text-base leading-7 text-slate-700">{level.copy}</p><p className="mt-2 text-sm leading-6 text-slate-500">{level.detail}</p><OpenCareChatButton className="mt-5 flex min-h-11 items-center gap-2 text-sm font-bold text-moss">Talk through this option <ArrowRight size={16} /></OpenCareChatButton></article>)}</div></section>
    <section id="care-costs" className="scroll-mt-24 py-5 sm:py-10"><CareCostCalculator /></section>
    <section className="my-14 rounded-[2rem] bg-ink px-6 py-10 text-white sm:px-10 sm:py-14"><div className="grid gap-8 md:grid-cols-[1fr_.8fr] md:items-center"><div><p className="eyebrow text-[#c2d7c8]">A more personal kind of help</p><h2 className="mt-3 font-serif text-4xl leading-tight sm:text-5xl">A local person beside you, not a call center.</h2></div><div><p className="text-base leading-7 text-slate-200">Senior Care Advisory provides face-to-face guidance for families across Raleigh, Durham, Cary, and nearby communities. A local provider network supports the service, so there is no charge to your family.</p><OpenCareChatButton className="mt-6 flex min-h-12 items-center gap-2 rounded-full bg-white px-5 font-bold text-ink">Meet your care companion <ArrowRight size={17} /></OpenCareChatButton></div></div></section>
    <section className="grid gap-4 pb-8 sm:grid-cols-3"><div className="rounded-2xl bg-[#f5f3ed] p-5"><p className="eyebrow">01 / Listen</p><p className="mt-2 text-lg font-bold">Start with what matters to your family.</p></div><div className="rounded-2xl bg-[#f5f3ed] p-5"><p className="eyebrow">02 / Compare</p><p className="mt-2 text-lg font-bold">See a few options that fit your needs.</p></div><div className="rounded-2xl bg-[#f5f3ed] p-5"><p className="eyebrow">03 / Decide</p><p className="mt-2 text-lg font-bold">Move at your pace, with a local advisor beside you.</p></div></section>
  </>;
}
